trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: echo "Building the application"
          - script: | # Add your build commands here
              # Example: npm install
              # Example: npm run build

  - stage: Test
    jobs:
      - job: Test
        steps:
          - script: echo "Running tests"
          - script: | # Add your test commands here
              # Example: npm test

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - script: echo 'This is the Deploy stage'
            displayName: 'Deploy'
  - task: PublishBuildArtifacts@1
