trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: echo "Building the application"

  - stage: Test
    jobs:
      - job: Test
        steps:
          - script: echo "Running tests"

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - script: echo "Deploying the application"
